### ISSUE TITLE
question

### ISSUE THREAD

**Issue by cordoval** [hostnet/dead#5]
so the idea is to do

```
auto_append_file="/your/path/to/append.php"
```
and that will get called on every file that gets opened for execution/invoked?

has this been proven with symfony/zf2 apps? wonder on the accuracy or if it interferes with some other framework mechanisms...

also is there a visualization tool for this or just the mysql view of things?

**Comment by hboomsma** [comment]
Hi Cordoval,

We started using a different approach because the append file was not called after a fatal error.
I'll try to update the wiki accordingly. For now it boils down to having a composer package with
a single file that is always auto loaded and than using `register_shutdown_function`.

We have an interface internally, that I am willing to publish on github, the code however is a bit focused on Hosted at the moment. I added a screenshot below.

![image](https://cloud.githubusercontent.com/assets/1465009/7676373/0ad729c8-fd43-11e4-9181-f4734e5d5134.png)

At Hostnet we use this project for several symfony2 applications.

Our Hostnet specific library looks like:

```json
{
    "name":        "hostnet/dead-lib",
    "description": "Report living files to invert the dead ones",
    "license":     "proprietary",
    "autoload" : {
        "files" : [ "src/register_shutdown.php" ]
    }
}
```
```php
// src/register_shutdown.php
$matches = array();
if (preg_match('#^/home/prod/([^/]+)/#', __DIR__, $matches)) {
    $app = $matches[1];
    register_shutdown_function(function($app) {
        // push all data to the browser
        @ob_flush();
        @flush();

        /* DYNAMIC LIVE FILE ANALYSIS */
        $db = new mysqli('<ip>', ''<user>', '<password>',  '<database>', <port>);
        $files = get_included_files();
        $matches = array();

        foreach ($files as &$file) {
            preg_match("#^/home/prod/$app/[^/]+(/.*)#", $file, $matches);
            if (isset($matches[1])) {
                $file = $matches[1];
            } else {
                unset($file);
            }
        }

        $files = implode('\',\'', $files);
        $query = "UPDATE $app
        SET count = count + 1, first_hit = if( first_hit IS NULL, NOW(), first_hit)
        WHERE file IN ('$files')";
        $db->real_query($query);
        $db->close();
    },  $app);
}
```

**Comment by hboomsma** [comment]
We also have an eclipse plugin hostnet/eclipse_plugin_dead, you can install it using
eclipse.hostnetbv.nl as update site

**Comment by cordoval** [comment]
@hboomsma that graphic application i wonder if that is sf2 and if it can be shared, would like to contribute or help with the bundle

**Comment by hboomsma** [comment]
@cordoval it is mostly javascript, If you want to create a nice bundle out of it I could share our current hostnet specific code with you (using github)

**Comment by cordoval** [comment]
yes that would be nice

i am still reading the document :) half way through but this would be nice

**Comment by hboomsma** [comment]
@cordoval https://github.com/hboomsma/dead
